<?php
/*----------Código Generado por --------------*/
/*-- Fecha : 22/11/2016 21:47:53--*/
/*-- Autores : Roy Alex Standen Barraza - Edson Carrasco Gonzales--*/
/*-- Contacto : roystandenb@gmail.com / edsoncarrascogonzalez@gmail.com --*/
error_reporting(E_ALL);
session_start();
include_once("../modelo/conexion.php");
include_once("../modelo/empresas.class.php");
if(isset($_SESSION['usuario'])){
@$ID_EMPRESAS_A_INTERVENIR = $_POST['ID_EMPRESAS_A_INTERVENIR'];
@$RUT_EMPRESAS_A_INTERVENIR	 = $_POST['RUT_EMPRESAS_A_INTERVENIR'];
@$NOMBRE_EMPRESAS_A_INTERVENIR = $_POST['NOMBRE_EMPRESAS_A_INTERVENIR'];
@$NOMBRE_FANTASIA_EMPRESAS_A_INTERVENIR = $_POST['NOMBRE_FANTASIA_EMPRESAS_A_INTERVENIR'];
@$NOMBRE_ADMINISTRADOR_EMPRESAS_A_INTERVENIR = $_POST['NOMBRE_ADMINISTRADOR_EMPRESAS_A_INTERVENIR'];
@$RUT_ADMINISTRADOR_EMPRESAS_A_INTERVENIR = $_POST['RUT_ADMINISTRADOR_EMPRESAS_A_INTERVENIR'];
@$MONTO_EMPRESAS_A_INTERVENIR = $_POST['MONTO_EMPRESAS_A_INTERVENIR'];
$accion = $_GET['accion'];
	if($accion=='crear'){
		$objeto = new empresas($ID_EMPRESAS_A_INTERVENIR,$RUT_EMPRESAS_A_INTERVENIR,$NOMBRE_EMPRESAS_A_INTERVENIR,$NOMBRE_FANTASIA_EMPRESAS_A_INTERVENIR,$NOMBRE_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$RUT_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$MONTO_EMPRESAS_A_INTERVENIR);
		print $objeto->crear();
	}else if($accion=='modificar'){
		$objeto = new empresas($ID_EMPRESAS_A_INTERVENIR,$RUT_EMPRESAS_A_INTERVENIR,$NOMBRE_EMPRESAS_A_INTERVENIR,$NOMBRE_FANTASIA_EMPRESAS_A_INTERVENIR,$NOMBRE_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$RUT_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$MONTO_EMPRESAS_A_INTERVENIR);
		print $objeto->modificar();
	}else if($accion=='eliminar'){
		$objeto = new empresas($ID_EMPRESAS_A_INTERVENIR,$RUT_EMPRESAS_A_INTERVENIR,$NOMBRE_EMPRESAS_A_INTERVENIR,$NOMBRE_FANTASIA_EMPRESAS_A_INTERVENIR,$NOMBRE_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$RUT_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$MONTO_EMPRESAS_A_INTERVENIR);
		print $objeto->eliminar();
	}else if($accion=='mostrar'){
		$objeto = new empresas($ID_EMPRESAS_A_INTERVENIR,$RUT_EMPRESAS_A_INTERVENIR,$NOMBRE_EMPRESAS_A_INTERVENIR,$NOMBRE_FANTASIA_EMPRESAS_A_INTERVENIR,$NOMBRE_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$RUT_ADMINISTRADOR_EMPRESAS_A_INTERVENIR,$MONTO_EMPRESAS_A_INTERVENIR);
		echo $objeto->mostrar($_POST['rut_empresa'],$_POST['nombre_empresa'],$_POST['nombre_fantasia_empresa'],$_POST['estado_legal'],$_POST['sector'],$_GET['jtSorting'],$_GET['jtStartIndex'],$_GET['jtPageSize']);
	}
}
?>